First draft of your first rule, add rule validator
sailpoint-oss/developer.sailpoint.com pull request #263
Opened 2023-06-09 14:40 UTC by tyler-mairose-sp

2023-06-09 17:34 UTC, colin-mckibben-sp requested changes
Some minor things to change.  I also noticed many grammatical errors.  Please have @james-haytko-sp review this as well for grammar, spelling, and style.

2023-06-09 17:34 UTC, colin-mckibben-sp commented on products/idn/docs/identity-now/rules/guides/index.md
> +description: Transform Guides
Transform or rule guides?

2023-06-09 17:34 UTC, colin-mckibben-sp commented on products/idn/docs/identity-now/rules/rule_validator.md
> +This utility is developed by SailPoint Technology Services, and its usage is covered via SailPoint Expert Services. If you have any issues, bugs, or feature requests, please submit them to SailPoint
Can you link to expert services?

2023-06-09 17:34 UTC, colin-mckibben-sp commented on products/idn/docs/identity-now/rules/guides/your_first_rule.md
> +## Attribute Generator rule
Please use title case for all section headers.  In this instance, "rule" needs to be capitalized.  Please review all other section headers for title case.

2023-06-21 14:57 UTC, james-haytko-sp approved these changes
I made some edits. Looks good!

2023-06-21 15:46 UTC, merged