Updated to fix inaccuracy
sailpoint-oss/developer.sailpoint.com pull request #431
Opened 2023-11-28 00:24 UTC by jordan-violet-sp

Fixed inaccuracy in how SaaS Connectivity leverages asymmetric keypair scheme.

2023-11-28 00:36 UTC, jordan-violet-sp commented on products/idn/docs/identity-now/saas-connectivity/index.md
> +SaaS connectors cannot operate the same way because they do not communicate through VA clusters. Despite this, SaaS connectors can still leverage the asymmetric key pair scheme—the key pair simply re
Done.

2023-11-28 00:36 UTC, james-haytko-sp approved these changes

2023-11-28 00:38 UTC, jordan-violet-sp commented
This pull request has been mentioned on **SailPoint Developer Community Forum**. There might be relevant details there:

https://developer.sailpoint.com/discuss/t/need-details-on-how-credentials-are-stored-for-saas-connectivity-connectors/21307/3

2023-11-28 17:45 UTC, philip-ellis-sp requested changes

2023-11-28 17:45 UTC, philip-ellis-sp commented on products/idn/docs/identity-now/saas-connectivity/index.md
> +SaaS connectors cannot operate the same way because they do not communicate through VA clusters. Despite this, SaaS connectors can still leverage the asymmetric key pair scheme — the key pair simply
do we want to remove the language around using the secret and secrettextarea field types?

2023-12-05 16:05 UTC, philip-ellis-sp approved these changes

2023-12-05 16:05 UTC, merged