updates for adding video library
sailpoint-oss/developer.sailpoint.com pull request #450
Opened 2023-12-11 16:28 UTC by darrell-thobe-sp

Starting point for video library

2024-04-06 00:43 UTC, jordan-violet-sp commented on src/pages/colab.js
> +                  Jump into our{' '}
@darrell-thobe-sp this text seems like it was left over and should be removed. If you read it on the built site in the PR, you'll see what I mean.

2024-04-06 00:43 UTC, jordan-violet-sp commented on src/pages/colab.js
> +                  <span className={styles.bold}>
@darrell-thobe-sp can you unbold this body?

2024-04-06 00:44 UTC, jordan-violet-sp commented on src/pages/blog.js
> +                  <span className={styles.bold}>
@darrell-thobe-sp can you unbold this?

2024-04-06 00:44 UTC, jordan-violet-sp requested changes
@darrell-thobe-sp take a lot at some of the comments I made on some text.

2024-04-08 13:57 UTC, tyler-mairose-sp approved these changes

2024-04-08 14:54 UTC, merged